### ISSUE TITLE
Hello, why can't I index this library in Android Studio?

### ISSUE THREAD

**Issue by XiaoYingYo** [libxposed/service#4]
@yujincheng08 
Hello, why can't I index this library in Android Studio?

The previous Could not find io.github.libxposed:api:100 also had a similar error, but I found the warehouse file in the actions of https://github.com/libxposed/api and downloaded it to my local warehouse. I don't know how to solve the problem of io.github.libxposed:service-interface:100, hope to get your reply!

Error message:
Configuration cache state could not be cached: field `importDirs` of task `:daemon:compileDebugAidl` of type `com.android.build.gradle.tasks.AidlCompile`: error writing value of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection'
> Could not resolve all files for configuration ':daemon:debugCompileClasspath'.
   > Could not find io.github.libxposed:service-interface:100.
     Required by:
         project :daemon

**Comment by yujincheng08** [comment]
this api is not yet widely tested so its not published to maven central. You can Goolgle how to use mavenLocal instread.

**Comment by 759852125** [comment]
> 此 api 尚未经过广泛测试，因此未发布到 Maven Central。您可以谷歌搜索如何使用 mavenLocal instread。

Thank you, please allow me to ask another question. After compiling the current project, I found that there are two aars, namely \interface\build\outputs\aar\interface-release.aar and service-master\service\build\outputs\ aar\service-release.aar ,
Do these two need to be installed through mvn install:install-file?

**Comment by XiaoYingYo** [comment]
> this api is not yet widely tested so its not published to maven central. You can Goolgle how to use mavenLocal instread.

Thank you, please allow me to ask another question. After compiling the current project, I found that there are two aars, namely \interface\build\outputs\aar\interface-release.aar and service-master\service\build\outputs\ aar\service-release.aar ,
Do these two need to be installed through mvn install:install-file?

**Comment by yujincheng08** [comment]
just run the gradle task `publishToMavenLocal`.

**Comment by XiaoYingYo** [comment]
> just run the gradle task `publishToMavenLocal`.

Great, thank you for your advice, I have been tinkering with it for a long time! Thank you very much
